"""domain schema

Creates the nine persistent entities of the Cryptiq pipeline: repositories,
scans, scan_jobs, findings, evidence, impact_nodes, review_items,
explanations and audit_events.

Revision ID: 42c2c7f7e9dc
Revises: dec2cc3d8453
Create Date: 2026-09-09 17:14:31.724117

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42c2c7f7e9dc"
down_revision: str | None = "dec2cc3d8453"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the domain tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'owner', 'name', name='uq_repositories_identity')
    )
    op.create_table('scans',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('base_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scan_status', native_enum=False, length=32), nullable=False),
    sa.Column('source_state', sa.Enum('LIVE', 'CACHED_REAL', 'UNAVAILABLE', name='source_state', native_enum=False, length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('pqc_ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_file_count', sa.Integer(), nullable=False),
    sa.Column('skipped_file_count', sa.Integer(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('ix_scans_commit_sha', ['commit_sha'], unique=False)
        batch_op.create_index('ix_scans_repository_id', ['repository_id'], unique=False)
        batch_op.create_index('ix_scans_status', ['status'], unique=False)

    op.create_table('findings',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('primitive', sa.String(length=128), nullable=False),
    sa.Column('library', sa.String(length=128), nullable=False),
    sa.Column('api', sa.String(length=255), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('start_column', sa.Integer(), nullable=True),
    sa.Column('end_column', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('SIGNATURE', 'KEY_EXCHANGE', 'ENCRYPTION', 'HASH', 'KEY_DERIVATION', 'RANDOMNESS', 'CERTIFICATE', 'UNKNOWN', name='cryptographic_role', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='review_priority', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'SUPPRESSED', name='finding_status', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'fingerprint', name='uq_findings_scan_fingerprint')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings_fingerprint', ['fingerprint'], unique=False)
        batch_op.create_index('ix_findings_priority', ['priority'], unique=False)
        batch_op.create_index('ix_findings_role', ['role'], unique=False)
        batch_op.create_index('ix_findings_scan_id', ['scan_id'], unique=False)

    op.create_table('scan_jobs',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scan_job_status', native_enum=False, length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_scan_jobs_scan_id', ['scan_id'], unique=False)
        batch_op.create_index('ix_scan_jobs_status', ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.Enum('SCAN_CREATED', 'SCAN_STARTED', 'SCAN_COMPLETED', 'SCAN_FAILED', 'FINDING_CREATED', 'REVIEW_STARTED', 'REVIEW_COMPLETED', 'EXPLANATION_REQUESTED', 'EXPLANATION_COMPLETED', name='audit_event_type', native_enum=False, length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_finding_id', ['finding_id'], unique=False)
        batch_op.create_index('ix_audit_events_scan_id', ['scan_id'], unique=False)

    op.create_table('evidence',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('repository_sha', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_finding_id'), ['finding_id'], unique=True)

    op.create_table('explanations',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='explanation_status', native_enum=False, length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('what_was_found', sa.Text(), nullable=True),
    sa.Column('what_it_means', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('review_action', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explanations_finding_id'), ['finding_id'], unique=False)

    op.create_table('impact_nodes',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('node_type', sa.Enum('ALGORITHM', 'API', 'FUNCTION', 'CLASS', 'MODULE', 'FILE', name='impact_node_type', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('relationship', sa.Enum('USES', 'CALLS', 'DEFINED_IN', 'CONTAINS', 'IMPORTS', name='impact_relationship', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impact_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_nodes_finding_id'), ['finding_id'], unique=False)

    op.create_table('review_items',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'REVIEWED', name='review_status', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index('ix_review_items_finding_id', ['finding_id'], unique=False)
        batch_op.create_index('ix_review_items_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the domain tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index('ix_review_items_status')
        batch_op.drop_index('ix_review_items_finding_id')

    op.drop_table('review_items')
    with op.batch_alter_table('impact_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_nodes_finding_id'))

    op.drop_table('impact_nodes')
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explanations_finding_id'))

    op.drop_table('explanations')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_finding_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_scan_id')
        batch_op.drop_index('ix_audit_events_finding_id')

    op.drop_table('audit_events')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_jobs_status')
        batch_op.drop_index('ix_scan_jobs_scan_id')

    op.drop_table('scan_jobs')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings_scan_id')
        batch_op.drop_index('ix_findings_role')
        batch_op.drop_index('ix_findings_priority')
        batch_op.drop_index('ix_findings_fingerprint')

    op.drop_table('findings')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('ix_scans_status')
        batch_op.drop_index('ix_scans_repository_id')
        batch_op.drop_index('ix_scans_commit_sha')

    op.drop_table('scans')
    op.drop_table('repositories')
    # ### end Alembic commands ###
